#!/bin/python3

import os
import sys

#
# Complete the dynamicArray function below.
#
def dynamicArray(n, queries):
    #
    # Write your code here.
    result=[]
    S=[[] for _ in range(n)]
    lastAnswer=0
    for q,x,y in queries:
        index=(x^lastAnswer) % n
        if q==1:
            S[index].append(y)
        if q==2:
            num = y % len(S[index])
            lastAnswer=S[index][num]
            print(lastAnswer)
            result.append(lastAnswer)
    return result


    #

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nq = input().split()

    n = int(nq[0])

    q = int(nq[1])

    queries = []

    for _ in range(q):
        queries.append(list(map(int, input().rstrip().split())))

    result = dynamicArray(n, queries)
    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
